// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQyJ8dMlS7qQUNe7FGgdICX-uC6ygb280',
    appId: '1:50128017659:android:6493026fdd99515e2df85e',
    messagingSenderId: '50128017659',
    projectId: 'quizapp-b85cd',
    storageBucket: 'quizapp-b85cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSLytFQAmbAYqLtVzes5XYcTJAOyTiTM4',
    appId: '1:50128017659:ios:58b5e9d1e4cfba472df85e',
    messagingSenderId: '50128017659',
    projectId: 'quizapp-b85cd',
    storageBucket: 'quizapp-b85cd.appspot.com',
    androidClientId: '50128017659-6n55k8eimgnllt558on8pi0r10dehleg.apps.googleusercontent.com',
    iosClientId: '50128017659-t91h3hltapmji57a82mt6t0o413cd49g.apps.googleusercontent.com',
    iosBundleId: 'com.techrokz.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSLytFQAmbAYqLtVzes5XYcTJAOyTiTM4',
    appId: '1:50128017659:ios:58b5e9d1e4cfba472df85e',
    messagingSenderId: '50128017659',
    projectId: 'quizapp-b85cd',
    storageBucket: 'quizapp-b85cd.appspot.com',
    androidClientId: '50128017659-6n55k8eimgnllt558on8pi0r10dehleg.apps.googleusercontent.com',
    iosClientId: '50128017659-t91h3hltapmji57a82mt6t0o413cd49g.apps.googleusercontent.com',
    iosBundleId: 'com.techrokz.myapp',
  );
}
